// AUTO-GENERATED by rorpc — do not edit manually.
// Re-generate: rorpc::generate_contract().output(path)

import { z } from "zod";
import { oc } from "@orpc/contract";
import { openapi } from "@orpc/openapi";
import { asyncIteratorObject } from "@orpc/contract";

// ============================================================================
// Input Types - Better Auth Rorpc Example Domain Models Planet
// ============================================================================

export const CreatePlanetInputSchema = z.object({
  name: z.string(),
  description: z.string().optional()
});

export type CreatePlanetInput = z.infer<typeof CreatePlanetInputSchema>;


// ============================================================================
// Domain Types - Better Auth Rorpc Example Domain Models Planet
// ============================================================================

export const PlanetSchema = z.object({
  id: z.number().int(),
  name: z.string(),
  description: z.string().optional()
});

export type Planet = z.infer<typeof PlanetSchema>;


// ============================================================================
// Input Types - Better Auth Rorpc Example Domain Models Planet
// ============================================================================

export const ListPlanetsPaginatedInputSchema = z.object({
  limit: z.number().int(),
  offset: z.number().int().optional()
});

export type ListPlanetsPaginatedInput = z.infer<typeof ListPlanetsPaginatedInputSchema>;


// ============================================================================
// Domain Types - Better Auth Rorpc Example Domain Models Planet
// ============================================================================

export const ListPlanetsPaginatedOutputSchema = z.object({
  items: z.array(PlanetSchema),
  next_page_param: z.number().int().optional()
});

export type ListPlanetsPaginatedOutput = z.infer<typeof ListPlanetsPaginatedOutputSchema>;


// ============================================================================
// Input Types - Better Auth Rorpc Example Domain Models Planet
// ============================================================================

export const DeletePlanetInputSchema = z.object({
  id: z.number().int()
});

export type DeletePlanetInput = z.infer<typeof DeletePlanetInputSchema>;


// ============================================================================
// SSE Event Types
// ============================================================================

export const EventDataSchema = z.object({
  message: z.string(),
  count: z.number().int()
});

export type EventData = z.infer<typeof EventDataSchema>;


// ============================================================================
// Enum Types
// ============================================================================

export const SseEventSchema = z.discriminatedUnion("type", [
  z.object({ type: z.literal("campaign_created"), data: z.object({ campaign_id: z.string(), title: z.string() }) }),
  z.object({ type: z.literal("campaign_status_changed"), data: z.object({ campaign_id: z.string(), status: z.string() }) }),
  z.object({ type: z.literal("campaign_progress"), data: z.object({ campaign_id: z.string(), sent: z.number().int(), total: z.number().int(), failed: z.number().int() }) })
]);

export type SseEvent = z.infer<typeof SseEventSchema>;


// ============================================================================
// Input Types - Better Auth Rorpc Example Domain Models Planet
// ============================================================================

export const FindPlanetQuerySchema = z.object({
  q: z.string().optional()
});

export type FindPlanetQuery = z.infer<typeof FindPlanetQuerySchema>;


// ============================================================================
// Domain Types - Better Auth Rorpc Example Domain Models Ping
// ============================================================================

export const PingResponseSchema = z.object({
  id: z.uuid(),
  message: z.string()
});

export type PingResponse = z.infer<typeof PingResponseSchema>;

// ============================================================================
// Error Schemas
// ============================================================================

const StandardApiErrors = {
  NOT_FOUND: {},
  INTERNAL: {
    data: z.object({ msg: z.string() })
  },
} as const;

// ============================================================================
// API Contract
// ============================================================================

export const contract = {
  ping: {
    ping: oc
      .meta(openapi({ method: "GET", path: "/ping" }))
      .input(z.void())
      .output(PingResponseSchema),
  },
  planet: {
    deletePlanet: oc
      .meta(openapi({ method: "DELETE", path: "/planet/{id}" }))
      .input(z.object({ id: z.number().int() }))
      .output(z.void())
      .errors(StandardApiErrors),
    createPlanet: oc
      .meta(openapi({ method: "POST", path: "/planet/" }))
      .input(CreatePlanetInputSchema)
      .output(PlanetSchema)
      .errors(StandardApiErrors),
    findPlanet: oc
      .meta(openapi({ method: "GET", path: "/planet/{id}" }))
      .input(z.object({ id: z.number().int() }).extend(FindPlanetQuerySchema.shape))
      .output(PlanetSchema)
      .errors(StandardApiErrors),
    listPlanetsPaginated: oc
      .meta(openapi({ method: "GET", path: "/planet/list-paginated" }))
      .input(ListPlanetsPaginatedInputSchema)
      .output(ListPlanetsPaginatedOutputSchema)
      .errors(StandardApiErrors),
    listPlanets: oc
      .meta(openapi({ method: "GET", path: "/planet/list" }))
      .input(z.void())
      .output(z.array(PlanetSchema))
      .errors(StandardApiErrors),
  },
  stream: {
    streamEvents: oc
      .meta(openapi({ method: "GET", path: "/stream" }))
      .input(z.void())
      .output(asyncIteratorObject(EventDataSchema)),
    streamCampaignEvents: oc
      .meta(openapi({ method: "GET", path: "/stream-campaigns" }))
      .input(z.void())
      .output(asyncIteratorObject(SseEventSchema)),
    streamEventsAsync: oc
      .meta(openapi({ method: "GET", path: "/stream-async" }))
      .input(z.void())
      .output(asyncIteratorObject(EventDataSchema)),
  },
} as const;

export type Contract = typeof contract;