// AUTO-GENERATED by rorpc — do not edit manually.
// Re-generate: rorpc::generate_contract().output(path)

import { z } from "zod";
import { oc } from "@orpc/contract";
import { openapi } from "@orpc/openapi";
import { asyncIteratorObject } from "@orpc/contract";

// ============================================================================
// Domain Types - Better Auth Rorpc Example Domain Models Ping
// ============================================================================

export const PingResponseSchema = z.object({
  id: z.uuid(),
  message: z.string()
});

export type PingResponse = z.infer<typeof PingResponseSchema>;

// ============================================================================
// Domain Types - Better Auth Rorpc Example Domain Models Planet
// ============================================================================

export const PlanetSchema = z.object({
  id: z.number().int(),
  name: z.string(),
  description: z.string().optional()
});

export type Planet = z.infer<typeof PlanetSchema>;

export const ListPlanetsPaginatedOutputSchema = z.object({
  items: z.array(PlanetSchema),
  next_page_param: z.number().int().optional()
});

export type ListPlanetsPaginatedOutput = z.infer<typeof ListPlanetsPaginatedOutputSchema>;

// ============================================================================
// Input Types - Better Auth Rorpc Example Domain Models Planet
// ============================================================================

export const CreatePlanetInputSchema = z.object({
  name: z.string(),
  description: z.string().optional()
});

export type CreatePlanetInput = z.infer<typeof CreatePlanetInputSchema>;

export const DeletePlanetInputSchema = z.object({
  id: z.number().int()
});

export type DeletePlanetInput = z.infer<typeof DeletePlanetInputSchema>;

export const FindPlanetQuerySchema = z.object({
  q: z.string().optional()
});

export type FindPlanetQuery = z.infer<typeof FindPlanetQuerySchema>;

export const ListPlanetsPaginatedInputSchema = z.object({
  limit: z.number().int(),
  offset: z.number().int().optional()
});

export type ListPlanetsPaginatedInput = z.infer<typeof ListPlanetsPaginatedInputSchema>;

// ============================================================================
// SSE Event Types
// ============================================================================

export const EventDataSchema = z.object({
  message: z.string(),
  count: z.number().int()
});

export type EventData = z.infer<typeof EventDataSchema>;

// ============================================================================
// Error Schemas
// ============================================================================

const StandardApiErrors = {
  NOT_FOUND: {},
  INTERNAL: {
    data: z.object({ msg: z.string() })
  },
} as const;

// ============================================================================
// API Contract
// ============================================================================

export const contract = {
  ping: {
    ping: oc
      .meta(openapi({ method: "GET", path: "/ping" }))
      .input(z.void())
      .output(PingResponseSchema),
  },
  planet: {
    deletePlanet: oc
      .meta(openapi({ method: "DELETE", path: "/planet/{id}" }))
      .input(z.object({ id: z.number().int() }))
      .output(z.void())
      .errors(StandardApiErrors),
    createPlanet: oc
      .meta(openapi({ method: "POST", path: "/planet/" }))
      .input(CreatePlanetInputSchema)
      .output(PlanetSchema)
      .errors(StandardApiErrors),
    findPlanet: oc
      .meta(openapi({ method: "GET", path: "/planet/{id}" }))
      .input(z.object({ id: z.number().int() }).extend(FindPlanetQuerySchema.shape))
      .output(PlanetSchema)
      .errors(StandardApiErrors),
    listPlanetsPaginated: oc
      .meta(openapi({ method: "GET", path: "/planet/list-paginated" }))
      .input(ListPlanetsPaginatedInputSchema)
      .output(ListPlanetsPaginatedOutputSchema)
      .errors(StandardApiErrors),
    listPlanets: oc
      .meta(openapi({ method: "GET", path: "/planet/list" }))
      .input(z.void())
      .output(z.array(PlanetSchema))
      .errors(StandardApiErrors),
  },
  stream: {
    streamEvents: oc
      .meta(openapi({ method: "GET", path: "/stream" }))
      .input(z.void())
      .output(asyncIteratorObject(EventDataSchema)),
    streamEventsAsync: oc
      .meta(openapi({ method: "GET", path: "/stream-async" }))
      .input(z.void())
      .output(asyncIteratorObject(EventDataSchema)),
  },
} as const;

export type Contract = typeof contract;